Dev backend
borodichyulia/Jobfinder-backend pull request #1
Opened 2022-06-06 11:21 UTC by borodichyulia

add index file and configuration files, and entity, controller and routes for resume

2022-06-09 11:25 UTC, kir-ostapchuk commented on src/data-source.ts
> +    username: "postgres",
please, remove credentials

2022-06-23 12:22 UTC, Viktarrudzenia commented on .gitignore
> +temp/
no newline at end of file

2022-06-23 12:23 UTC, Viktarrudzenia commented on src/.env
> +CLIENT_URL=https://yandex.ru/
no newline at end of file

2022-06-23 12:24 UTC, Viktarrudzenia commented on src/controller/ApplicantProfileController.ts
> +    // }
do we really need this commented function here?

2022-06-23 12:25 UTC, Viktarrudzenia commented on src/controller/ApplicantProfileController.ts
> +}
no newline

2022-06-23 12:25 UTC, Viktarrudzenia commented on src/controller/ApplicantProfileController.ts
> +    // }
do we really need this commented function here?

2022-06-23 12:26 UTC, Viktarrudzenia commented on src/controller/ApplicantProfileController.ts
> +import { NextFunction, Request, Response } from "express"
!This comment about all files inside the project.
add prettier settings to the project and format with prettier all files

2022-06-23 12:26 UTC, Viktarrudzenia commented on package.json
> +      "@types/uuid": "^8.3.4",
can we move them to devDependencies?

2022-06-23 12:27 UTC, Viktarrudzenia commented on package.json
> +      "typeorm": "0.3.6",
can we move it to devDependencies?

2022-06-23 12:28 UTC, Viktarrudzenia commented on src/controller/CompanyProfileController.ts
> +import { CompanyProfile } from "../entity/CompanyProfile"
can we separate imports from 3rd parties and from our project?

import express
import from project
->
import express 

import from project
?

2022-06-23 12:29 UTC, viktar-rudzenia commented on src/controller/CompanyProfileController.ts
> +
prettier

2022-06-23 12:29 UTC, viktar-rudzenia commented on src/controller/CompanyProfileController.ts
> +}
no newline

2022-06-23 12:29 UTC, Viktarrudzenia commented on src/controller/ResumeController.ts
> +import { Resume } from "../entity/Resume"
let's separate imports

2022-06-23 12:30 UTC, Viktarrudzenia commented on src/controller/ResumeController.ts
> +}
prettier + newline

2022-06-23 12:30 UTC, viktar-rudzenia commented on src/controller/ResumeController.ts
> +            contacts: contacts
can we optimize here?
{somevar: somevar} === {somevar} ?

2022-06-23 12:32 UTC, Viktarrudzenia commented on src/controller/UserController.ts
> +import { NextFunction, Request, Response } from "express"
lets add new line after third party imports

2022-06-23 12:32 UTC, viktar-rudzenia commented on src/controller/UserController.ts
> +
unnecessary lines

2022-06-23 12:32 UTC, Viktarrudzenia commented on src/controller/UserController.ts
> +    // }
do we really need this?

2022-06-23 12:32 UTC, Viktarrudzenia commented on src/controller/UserController.ts
> +            console.log('hello');
unnecessary console log

2022-06-23 12:33 UTC, Viktarrudzenia commented on src/controller/UserController.ts
> +}
no new line + unnecessary new lines

2022-06-23 12:33 UTC, Viktarrudzenia commented on src/controller/VacancyController.ts
> +import { Vacancy } from "../entity/Vacancy"
new line

2022-06-23 12:33 UTC, Viktarrudzenia commented on src/controller/VacancyController.ts
> +            contacts: contacts
optimize here

2022-06-23 12:34 UTC, Viktarrudzenia commented on src/controller/VacancyController.ts
> +}
no new line at the end + extra new lines

2022-06-23 12:34 UTC, Viktarrudzenia commented on src/controller/VacancyController.ts
> +        console.log(request.params.id);
unnecessary console log?

2022-06-23 12:34 UTC, Viktarrudzenia commented on src/controller/VacancyController.ts
> +        let vacancyToRemove = await vacancyRepository.findBy({ id: request.params.id });
why we use 'let' here? mb better to use `const` ?

2022-06-23 12:35 UTC, Viktarrudzenia commented on src/data-source.ts
> +import { Resume } from "./entity/Resume"
can we add new line?

2022-06-23 12:36 UTC, viktar-rudzenia commented on src/dtos/user-dto.ts
> +}
we can remove 11 line and add the new line at the end of file

2022-06-23 12:36 UTC, Viktarrudzenia commented on src/dtos/user-dto.ts
> +        this.isActivated=model.isActivated;
prettier

2022-06-23 12:36 UTC, Viktarrudzenia commented on src/entity/ApplicantProfile.ts
> +}
no new line

2022-06-23 12:36 UTC, Viktarrudzenia commented on src/entity/CompanyProfile.ts
> +}
no new line at the end of file

2022-06-23 12:38 UTC, Viktarrudzenia commented on src/entity/Vacancy.ts
> +import { Entity, PrimaryGeneratedColumn, Column } from "typeorm"
! to all files, fix: 
1. add prettier and format all files
2. add a new line at the end of the file where not existed
3. remove unnecessary console.log \ comments and new lines

2022-06-23 12:40 UTC, Viktarrudzenia commented on src/index.ts
> +    console.log("Express server has started on port 3000. Open http://localhost:3000/users to see results")
can we add real PORT here? because we use proccess.env.PORT

2022-06-23 12:40 UTC, viktar-rudzenia commented on src/middleware/error-middleware.ts
> +    console.log(err);
do we need this comment?

2022-06-23 12:41 UTC, Viktarrudzenia commented on src/routes/ApplicantProfileRoutes.ts
> +// },
do we need this comment?

2022-06-23 12:41 UTC, Viktarrudzenia commented on src/routes/ApplicantProfileRoutes.ts
> +// },
do we need it?

2022-06-23 12:41 UTC, Viktarrudzenia commented on src/routes/UserRoutes.ts
> +// },
do we need this comment?

2022-06-23 12:42 UTC, Viktarrudzenia commented on src/service/mail-service.ts
> +                pass: "MDarC2caUxd9u3XRKg1D" //password is wrong
can we add this info to .env and use it from .env ?

2022-06-23 12:42 UTC, Viktarrudzenia commented on src/service/token-service.ts
> +        // }
do we need this comment?

2022-06-23 12:43 UTC, viktar-rudzenia commented on src/service/user-service.ts
> +import { AppDataSource } from "../data-source"
lets move this import to imports from our project

2022-06-23 12:43 UTC, Viktarrudzenia commented on src/service/user-service.ts
> +        await mailService.sendActivationMail(email, `http://localhost:3000/users/activate/${activationLink}`);
let's use PORT variable from .env?

2022-06-23 12:43 UTC, Viktarrudzenia commented on src/service/user-service.ts
> +        console.log(userDto);
unnecessary console .log?

2022-06-23 12:44 UTC, Viktarrudzenia commented on src/service/user-service.ts
> +        const user1 = await userRepository.save(user);
let's rename user1 to something more descriptive

2022-06-23 12:46 UTC, Viktarrudzenia requested changes
looks fine, just fix the comments please,
! to all files, fix: 
1. add prettier and format all files
2. add a new line at the end of the file where needed
3. remove unnecessary console.log \ comments and new lines
4. check import sequences
Then ping me in skype for further details :)

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/CompanyProfileController.ts
> +    console.log(request.params.id);
Ненужные консоль логи надо удалять. Можно даже добавить правило в линтер, чтоб они подсвечивались. Если же необходимо логгировать какую-то информацию, то стоит подключать какие-нибудь логгеры.

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/CompanyProfileController.ts
> +    let vacancyToRemove = await companyProfileRepository.findBy({
Если переменная не переопределяется, лучше использовать const

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/ResumeController.ts
> +    let profileToRemove = await resumeRepository.findBy({
Если не планируется переопределять переменную - то стоит использовать const

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/UserController.ts
> +      console.log('hello');
ненужные консоль логи нужно удалять

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/ResumeController.ts
> +    console.log(request.params.id);
То же самое про консоль лог

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/UserController.ts
> +  // async login(req, res, next) {
Ненужный закомментированный код тоже надо убирать

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/UserController.ts
> +      return res.redirect('https://yandex.ru/');
Урлы лучше хранить в переменной, в .env

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/exeptions/api-error.ts
> +    return new ApiError(401, 'Пользователь не авторизован');
Такие сообщения лучше выносить куда-нибудь в константу

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/index.ts
> +      origin: 'http://localhost:3001',
Этот урл тоже надо в .env

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/index.ts
> +      'Express server has started on port 3000. Open http://localhost:3000/users to see results'
Не критично, но даже в целях общего развития, лучше подключить логгер. И в сообщении значения port и url нужно брать из .env

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/middleware/error-middleware.ts
> +  return res.status(500).json({ message: 'Непредвиденная ошибка' });
Так же рекомендую вынести сообщение в константу. Можно создать файл, например errorMessages.js, и там хранить все сообщения об ошибках

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/service/user-service.ts
> +      `http://localhost:3000/activate/${activationLink}`
Часть с url должна быть взята из .env

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/.env
> +CLIENT_URL=https://yandex.ru/
.env нужно добавить в .gitignore, а в репозитории создать файл .env.example, где будут фейковые примеры переменных

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/ApplicantProfileController.ts
> +export class ApplicantProfileController {
я бы тут добавила пустую строку перед объявлением класса

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/controller/UserController.ts
> +        maxAge: 30 * 24 * 60 * 60 * 1000,
Лучше такое тоже сохранять в константы с человекочитаемыми именами. Например 
const THIRTY_DAYS = 30 * 24 * 60 * 60 * 1000;

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/entity/Resume.ts
> +}
Бывает полезно добавлять колонки с датой создания и обновления записи. Но это не обязательно

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/service/mail-service.ts
> +        pass: 'MDarC2caUxd9u3XRKg1D',
Выглядит, как какая-то секьюрная информация, которая должна быть в .env

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/service/mail-service.ts
> +      from: 'jobfinder01@mail.ru',
Это тоже надо хранить в переменных среды

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/service/token-service.ts
> +      const token1 = await tokenRepository.save(tokenData);
выглядит как плохая практика, использовать такие имена переменных - token1. Может просто сразу вернуть результат seve, не сохраняя его в переменную?

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/service/token-service.ts
> +    const token = await tokenRepository.save(newToken);
а нельзя раве сразу сделать save, без предварительного create?
и тоже можно не сохранять в переменную

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/service/user-service.ts
> +      throw ApiError.BadRequest('Неккоректная ссылка активации');
в слове Некорректная две опечатки, и лучше вынести сообщение в переменную

2022-06-28 11:08 UTC, MarynaBandarenka commented on src/dtos/user-dto.ts
> +  email;
стоит добавить в этот слой (dto) валидацию данных

2022-10-13 10:42 UTC, merged